s="Hello class"
#print(s)
#print(s.lower())
#print(s.upper())
#print(s.title())
#print(s.capitalize())
#print(s.swapcase())
#print(s.rstrip("s"))
#print(s.lstrip("h"))
#print(s.count('e'))
#print(s.center(50))
#print(s.split())
#print(s.index('w'))
#print(s.find('h'))
#print(s.__len__())
#print(s[4])
s1=s[1:]
print(s1)
s1=s[:11]
print(s1)
s1=s[0:10]
print(s1)
s1=s[1:7:2]
print(s1)
s1=s[:]
print(s1)
s1=s[::]
print(s1)
s1=s[::-1]
print(s1)
s1=s[-5]
print(s1)
s1=s[-2:-5:-1]
print(s1)
s1=s[:6:-2]
print(s1)
s1=s[3::-1]
print(s1)
s1=s[3:2:-1]
print(s1)
s1=s[3:-1:-1]
print(s1)
